# 0) Importing the right tools <font color='blue'> (5 min) </font>

### <font color='red'>0.1) Import the necessary packages with their usual aliases: </font>

- pandas as pd
- numpy as np
- seaborn as sns
- matplotlib.pyplot as plt

In [1]:
from __future__ import division
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

#### IMPORT THE USUAL PACKAGES WITH THEIR ALIASES ####

import warnings
warnings.filterwarnings('ignore')

%pylab inline

Populating the interactive namespace from numpy and matplotlib


### <font color='red'>0.2) Import the dataset from <i>'../data/input_data_for_modeling_purpose.csv'</i></font>

In [2]:
raw_data = pd.read_csv('input_data_for_modeling_purpose.csv')
#### IMPORT AND READ THE CSV DATA USING pd.read_csv() #### 

### <font color='red'>0.3) Copy the raw_data, print samples, and prepare features & labels for training & testing</font>

In [3]:
data = raw_data.copy()
#### COPY THE RAW DATA WITH THE .copy() FUNCTION ####

In [4]:
data.head()
#### PRINT SAMPLES USING .sample() AND CHECK THE FEATURES ####

tripduration  start station latitude  start station longitude  \
0          1338               40.727103               -74.002971   
1           290               40.727791               -73.985649   
2           634               40.735238               -74.000271   
3           159               40.716059               -73.991908   
4          1233               40.734927               -73.992005   

   end station latitude  end station longitude    usertype  june_day  \
0             40.759291             -73.988597  Subscriber         1   
1             40.722055             -73.989111  Subscriber         1   
2             40.749718             -74.002950  Subscriber         1   
3             40.718939             -73.992663  Subscriber         1   
4             40.710451             -73.960876    Customer         1   

   traveled_distance  average_speed  start_day_Friday  start_day_Monday  \
0           3.778532      10.166454                 0                 1   
1           0.701381       8.706796                 0                 1   
2           1.625823       9.231803                 0                 1   
3           0.326548       7.393548                 0                 1   
4           3.780067      11.036692                 0                 1   

   start_day_Saturday  start_day_Sunday  start_day_Thursday  \
0                   0                 0                   0   
1                   0                 0                   0   
2                   0                 0                   0   
3                   0                 0                   0   
4                   0                 0                   0   

   start_day_Tuesday  start_day_Wednesday  is_weekend_0  is_weekend_1  \
0                  0                    0             1             0   
1                  0                    0             1             0   
2                  0                    0             1             0   
3                  0                    0             1             0   
4                  0                    0             1             0   

   start_moment_afternoon  start_moment_evening  start_moment_morning  \
0                       0                     0                     0   
1                       0                     0                     0   
2                       0                     0                     0   
3                       0                     0                     0   
4                       0                     0                     0   

   start_moment_night  is_circle_trip_0  is_circle_trip_1  
0                   1                 1                 0  
1                   1                 1                 0  
2                   1                 1                 0  
3                   1                 1                 0  
4                   1                 1                 0

In [5]:
data.shape

(935588, 24)

In [6]:
labels = np.array(data.usertype)
del data['usertype']
features = np.array(data)

In [7]:
print(labels)

['Subscriber' 'Subscriber' 'Subscriber' ... 'Customer' 'Subscriber'
 'Subscriber']


In [8]:
print(features)

[[ 1.33800000e+03  4.07271026e+01 -7.40029709e+01 ...  1.00000000e+00
   1.00000000e+00  0.00000000e+00]
 [ 2.90000000e+02  4.07277913e+01 -7.39856494e+01 ...  1.00000000e+00
   1.00000000e+00  0.00000000e+00]
 [ 6.34000000e+02  4.07352380e+01 -7.40002710e+01 ...  1.00000000e+00
   1.00000000e+00  0.00000000e+00]
 ...
 [ 3.55700000e+03  4.07545573e+01 -7.39659298e+01 ...  1.00000000e+00
   1.00000000e+00  0.00000000e+00]
 [ 8.19000000e+02  4.07206644e+01 -7.39851798e+01 ...  1.00000000e+00
   1.00000000e+00  0.00000000e+00]
 [ 6.67000000e+02  4.07130792e+01 -7.39985119e+01 ...  1.00000000e+00
   1.00000000e+00  0.00000000e+00]]


In [9]:
import sklearn
from sklearn.preprocessing import label_binarize
binarized_labels = label_binarize(labels, classes=['Customer', 'Subscriber']).ravel() 
#### BINARIZE THE LABELS OF THE DATASET, AND RAVEL THE RESULT USING .ravel() ####
                   #### Subscriber will be label 1, Customer label 0 ####
                   #### This will be a binary classifiation problem ####

In [10]:
print(binarized_labels)

[1 1 1 ... 0 1 1]


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, binarized_labels, test_size=0.3, random_state = 27)
#### SPLIT BETWEEN TRAIN AND TEST ####

# 1) Model Selection <font color='blue'> (40 min) </font>

In [12]:
# !pip install -U scikit-learn
import sklearn

### <font color='red'>1.1) Logistic Regression </font>

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
lr = LogisticRegression()
score = cross_val_score(lr, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Logistic Regression Average Score: ', score.mean())

[0.8198743  0.81675639 0.81547099]
Logistic Regression Average Score:  0.8173672238551507


### <font color='red'>1.2) Nearest Neighbors </font>

In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
score = cross_val_score(knn, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('KNN Average Score: ', score.mean())

[0.7350128  0.73709777 0.73323898]
KNN Average Score:  0.7351165175528248


### <font color='red'>1.3) Gaussian Naive Bayes </font>

In [15]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
score = cross_val_score(nb, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Naive Bayes Average Score: ', score.mean())

[0.77463431 0.77148516 0.77332766]
Naive Bayes Average Score:  0.7731490439211871


### <font color='red'>1.4) Neural Network </font>

In [16]:
from sklearn.neural_network import MLPClassifier
nn = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(5, 2), random_state=1)
score = cross_val_score(nn, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Neural Network Average Score: ', score.mean())

[0.5 0.5 0.5]
Neural Network Average Score:  0.5


### <font color='red'>1.5) Decision Tree </font>

In [17]:
from sklearn import tree
dt = tree.DecisionTreeClassifier()
score = cross_val_score(dt, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Decision Tree Average Score: ', score.mean())

[0.69170817 0.69462785 0.69398252]
Decision Tree Average Score:  0.6934395133227657


### <font color='red'>1.6) Random Forest </font>

In [17]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 10)
score = cross_val_score(rf, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Random Forest Average Score: ', score.mean())

[0.82891955 0.83021024 0.82917379]
Random Forest Average Score:  0.8294345252803316


# 2) Hyperparameter Tuning <font color='blue'> (45 min) </font>

### <font color='red'>2.1) Please use help function to have a better understanding about RandomForestClassifier and hyperparameters that can be tuned </font>

In [24]:
help(RandomForestClassifier)

Help on class RandomForestClassifier in module sklearn.ensemble._forest:

class RandomForestClassifier(ForestClassifier)
 |  RandomForestClassifier(n_estimators=100, *, criterion='gini', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, warm_start=False, class_weight=None, ccp_alpha=0.0, max_samples=None)
 |  
 |  A random forest classifier.
 |  
 |  A random forest is a meta estimator that fits a number of decision tree
 |  classifiers on various sub-samples of the dataset and uses averaging to
 |  improve the predictive accuracy and control over-fitting.
 |  The sub-sample size is controlled with the `max_samples` parameter if
 |  `bootstrap=True` (default), otherwise the whole dataset is used to build
 |  each tree.
 |  
 |  Read more in the :ref:`User Guide <forest>`.
 |  
 |  P

### <font color='red'>2.1) Please try to change several hyperparameters in RandomForestClassifier to improve model performance </font>

#### n_estimators

In [25]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 20)
score = cross_val_score(rf, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Random Forest Average Score: ', score.mean())

[0.84789426 0.84806974 0.84485508]
Random Forest Average Score:  0.8469396897652284


In [18]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 50)
score = cross_val_score(rf, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Random Forest Average Score: ', score.mean())

[0.86053835 0.86121812 0.85802469]
Random Forest Average Score:  0.8599270553133719


#### max_depth

In [27]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 50, max_depth = 10)
score = cross_val_score(rf, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Random Forest Average Score: ', score.mean())

[0.84131993 0.83912412 0.83760142]
Random Forest Average Score:  0.839348493516563


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 50, max_depth = 20)
score = cross_val_score(rf, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Random Forest Average Score: ', score.mean())

#### max_features

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 50, max_depth = 20, max_features = 5)
score = cross_val_score(rf, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Random Forest Average Score: ', score.mean())

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 50, max_depth = 20, max_features = 10)
score = cross_val_score(rf, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Random Forest Average Score: ', score.mean())

In [21]:
rf.fit(X_train, y_train) # fit the final model

RandomForestClassifier(n_estimators=10)

In [22]:
lr.fit(X_train, y_train) # fit the final model

LogisticRegression()

In [23]:
nb.fit(X_train, y_train) # fit the final model

GaussianNB()

In [24]:
knn.fit(X_train, y_train) # fit the final model

KNeighborsClassifier()

### <font color='red'>2.3) Save the final model </font>

In [18]:
import pickle

In [19]:
import os
# os.chdir('/Users/auzantamtama/Downloads/module_w4') # << Ganti directory folder

In [20]:
os.getcwd() # << Cek current folder directory

'C:\\Users\\dell\\Punya Faris\\Global Class - Data Science\\Week 4'

In [25]:
# export model as a pickle object
filename = 'randomforest.pkl'
pickle.dump(rf, open(filename, 'wb'))

In [26]:
filename = 'logisticregression.pkl'
pickle.dump(lr, open(filename, 'wb'))

In [27]:
filename = 'gaussiannb.pkl'
pickle.dump(nb, open(filename, 'wb'))

In [28]:
filename = 'kneighborsclassifier.pkl'
pickle.dump(knn, open(filename, 'wb'))

# 3) Exercise - Please be creative and try to improve model performance <font color='blue'> (20 min) </font>

In [36]:
from sklearn.model_selection import GridSearchCV

max_depth = [80, 100, 120, 140]
criterion = ["gini", "entropy", "log_loss"]
max_features = [1, 2, 3, 4]
min_samples_leaf = [3, 4, 5]
min_samples_split = [8, 10, 12, 14]
n_estimators = [100, 200, 300]

param_grid = {'max_depth': max_depth, 'criterion': criterion, 'max_features': max_features, \
              'min_samples_leaf': min_samples_leaf, 'min_samples_split': min_samples_split, 'n_estimators': n_estimators}

rf_tuning = RandomForestClassifier()

rf_tuning_cv = GridSearchCV(rf_tuning, param_grid, cv = 3)

rf_tuning_cv.fit(X_train, y_train)

print("Tuned Random Forest Parameters: {}".format(rf_tuning_cv.best_params_))
print("Best score is {}".format(rf_tuning_cv.best_score_))

KeyboardInterrupt: 